"use client";

import { useEffect, useState } from "react";
import { ArrowRight, ChevronLeft, ChevronRight, MessageCircle, Search } from "lucide-react";

type Finish = { id: string; name: string; accent: string; colorFile: string; frontFile: string; detailFile: string };

const asset = (folder: string, file: string) => `/assets/iphone-17-pro-max/${folder}/${file}`;
const transparent = (folder: string, file: string) => asset(folder, `transparent/${file}`);

const finishes: Finish[] = [
  { id: "cosmic-orange", name: "Cosmic Orange", accent: "#f78a43", colorFile: "cosmic-orange.webp", frontFile: "cosmic-orange-front.webp", detailFile: "cosmic-orange-detail.webp" },
  { id: "deep-blue", name: "Deep Blue", accent: "#7180a8", colorFile: "deep-blue.webp", frontFile: "deep-blue-front.webp", detailFile: "deep-blue-detail.webp" },
  { id: "silver", name: "Silver", accent: "#d9dce0", colorFile: "silver.webp", frontFile: "silver-front.webp", detailFile: "silver-detail.webp" },
];

const nav = [["Início", "hero"], ["Produto", "produto"], ["Galeria", "galeria"], ["Detalhes", "detalhes"], ["Contato", "contato"]];

export default function Home() {
  const [finish, setFinish] = useState(0);
  const [leftFinish, setLeftFinish] = useState(0);
  const [rightFinish, setRightFinish] = useState(1);
  const [compare, setCompare] = useState(50);
  const [menu, setMenu] = useState(false);
  const [lightbox, setLightbox] = useState<string | null>(null);

  useEffect(() => {
    const onScroll = () => {
      const max = document.documentElement.scrollHeight - window.innerHeight;
      document.documentElement.style.setProperty("--scroll", `${max ? (window.scrollY / max) * 100 : 0}%`);
      document.getElementById("nav")?.classList.toggle("is-scrolled", window.scrollY > 36);
    };
    window.addEventListener("scroll", onScroll, { passive: true }); onScroll(); document.body.classList.add("is-ready");
    return () => window.removeEventListener("scroll", onScroll);
  }, []);

  useEffect(() => { document.documentElement.style.setProperty("--hero-accent", finishes[finish].accent); }, [finish]);
  const current = finishes[finish];
  const whatsapp = (message: string) => `https://wa.me/5511999999999?text=${encodeURIComponent(`Olá! Tenho interesse no iPhone 17 Pro Max ${message}.`)}`;

  return <div className="reference-site product-17-site">
    <div className="grain" aria-hidden="true" /><div className="scroll-progress" aria-hidden="true" />
    <header className={`nav ${menu ? "is-open" : ""}`} id="nav">
      <a href="#hero" className="nav__brand"><span className="dot" />V�?RTICE</a>
      <nav className="nav__links" aria-label="Navegação principal">{nav.map(([label, id]) => <a key={id} href={`#${id}`}>{label}</a>)}</nav>
      <div className="nav__actions"><button className="nav__icon-btn" aria-label="Buscar"><Search size={18} /></button><a className="nav__wa" href={whatsapp("falar com um especialista")} target="_blank" rel="noreferrer"><MessageCircle size={15} /><span>Falar no WhatsApp</span></a><button className="nav__burger" onClick={() => setMenu(!menu)} aria-label="Abrir menu" aria-expanded={menu}><span /><span /><span /></button></div>
    </header>
    <div className={`mobile-menu ${menu ? "is-open" : ""}`}><nav>{nav.map(([label, id]) => <a key={id} href={`#${id}`} onClick={() => setMenu(false)}>{label}</a>)}</nav></div>

    <main>
      <section className="hero" id="hero"><div className="hero__ambient hero__ambient--one" /><div className="hero__ambient hero__ambient--two" /><div className="hero__inner"><div className="hero__copy"><p className="hero__kicker">Uma nova era Pro</p><h1><span className="line"><span>iPhone 17</span></span><span className="line"><span>Pro Max.</span></span><span className="line"><span>Feito para ir além.</span></span></h1><p className="hero__sub">O iPhone 17 Pro Max combina construção refinada, desempenho excepcional e um sistema de câmeras criado para acompanhar as suas maiores ideias.</p><div className="hero__ctas"><a href="#produto" className="btn btn--primary">Conhecer o produto <ArrowRight size={16} /></a><a href="#galeria" className="btn btn--ghost">Explorar imagens</a></div><div className="hero__meta"><div className="meta-chip"><strong>iPhone 17 Pro Max</strong><span>�snico modelo da coleção</span></div><div className="meta-chip"><strong>256 GB</strong><span>Consulte disponibilidade</span></div><div className="meta-chip"><strong>{current.name}</strong><span>Escolha o acabamento</span></div></div><div className="finish-picker" role="group" aria-label="Escolha a cor do iPhone 17 Pro Max">{finishes.map((item, i) => <button key={item.id} className={`finish-btn ${finish === i ? "is-active" : ""}`} onClick={() => setFinish(i)} aria-label={item.name} title={item.name}><span style={{ "--swatch": item.accent } as React.CSSProperties} /></button>)}</div></div><div className="hero__visual"><div className="hero__glow" /><div className="hero__stage"><div className="hero__device"><img src={transparent("angles", current.frontFile)} alt={`iPhone 17 Pro Max ${current.name}`} /></div><div className="hero__orbit hero__orbit--1" /><div className="hero__orbit hero__orbit--2" /></div><div className="hero__floating hero__floating--top"><span>Produto oficial</span><strong>17 Pro Max</strong></div><div className="hero__floating hero__floating--bottom"><span>Acabamento</span><strong>{current.name}</strong></div></div></div><div className="hero__scrollcue"><span>Role para explorar</span><span className="line" /></div></section>

      <section className="highlights section-pad" id="produto"><div className="container"><div className="section-head"><div><p className="section-label">iPhone 17 Pro Max</p><h2>Uma experiência inteira dedicada ao mesmo produto.</h2></div><p>As fotos oficiais mantêm o acabamento, a proporção e os detalhes do aparelho em todos os momentos da navegação.</p></div></div><div className="highlights__rail-wrap"><div className="highlights__rail"><article className="highlight-card highlight-card--wide"><div className="highlight-card__copy"><span>01</span><h3>O protagonista da página.</h3><p>Uma composição oficial apresenta o iPhone 17 Pro Max com presença e espaço.</p></div><img src={transparent("hero", "iphone-17-pro-max-main.webp")} alt="iPhone 17 Pro Max" /></article><article className="highlight-card"><div className="highlight-card__copy"><span>02</span><h3>Três acabamentos.</h3><p>Cosmic Orange, Deep Blue e Silver, cada um com seu próprio asset oficial.</p></div><img src={transparent("angles", current.frontFile)} alt={`iPhone 17 Pro Max ${current.name}`} /></article><article className="highlight-card"><div className="highlight-card__copy"><span>03</span><h3>Detalhes reais.</h3><p>�,ngulos e câmeras preservados a partir das imagens fornecidas.</p></div><img src={transparent("angles", current.detailFile)} alt={`Detalhe do iPhone 17 Pro Max ${current.name}`} /></article></div></div></section>

      <section className="gallery section-pad" id="galeria"><div className="container"><div className="section-head"><div><p className="section-label">Galeria oficial</p><h2>O mesmo iPhone, visto de todos os ângulos.</h2></div><p>Nenhuma imagem externa ou mockup genérico: somente as fotos oficiais enviadas para este produto.</p></div><div className="gallery__grid">{[[transparent("hero", "iphone-17-pro-max-main.webp"), "Hero", "iPhone 17 Pro Max"], [transparent("angles", current.frontFile), "Frontal e traseiro", current.name], [transparent("angles", current.detailFile), "�,ngulo de detalhe", "Sistema de câmeras"], [transparent("angles", "deep-blue-front.webp"), "Coleção", "Acabamentos oficiais"]].map(([src, small, title], i) => <button key={src} className={`gallery__item ${i === 0 ? "gallery__item--hero" : ""} ${i === 3 ? "gallery__item--dark" : ""}`} onClick={() => setLightbox(src)}><img src={src} alt={`${title} do iPhone 17 Pro Max`} /><span className="gallery__cap"><small>{small}</small>{title}</span></button>)}</div></div></section>

      <section className="camera-story section-pad" id="detalhes"><div className="container"><div className="section-head"><div><p className="section-label">Construção Pro</p><h2>Detalhes que continuam fiéis ao produto.</h2></div><p>Acabamento, câmeras e laterais são apresentados com as imagens oficiais, sem filtros ou recoloração.</p></div><div className="camera-story__grid"><div className="camera-story__visual"><div className="camera-story__visual-inner"><div className="camera-story__light" /><img src={transparent("angles", current.detailFile)} alt={`Detalhe do iPhone 17 Pro Max ${current.name}`} /></div></div><div className="camera-story__copy">{[["01", "Sistema de câmeras Pro.", "Uma imagem de detalhe para observar lentes, bordas e construção do aparelho."], ["02", "Acabamento sem alterações.", "Cada cor é carregada a partir do arquivo oficial correspondente, sem filtros CSS."], ["03", "Proporções preservadas.", "Os ângulos fornecidos mantêm o formato original do iPhone 17 Pro Max."]].map(([n, title, text]) => <article className="camera-point is-active" key={n}><span>{n}</span><h3>{title}</h3><p>{text}</p></article>)}</div></div></div></section>

      <section className="compare section-pad" id="cores"><div className="container"><div className="section-head"><div><p className="section-label">Comparação de acabamentos</p><h2>Escolha o que aparece em cada lado.</h2></div><p>Selecione duas cores oficiais e arraste o controle para comparar o iPhone 17 Pro Max sem alterar suas características.</p></div><div className="compare__selectors"><div className="compare__selector"><span>Esquerda</span><div className="compare__swatches">{finishes.map((item, i) => <button key={`left-${item.id}`} className={leftFinish === i ? "is-active" : ""} disabled={rightFinish === i} onClick={() => setLeftFinish(i)} aria-label={`Usar ${item.name} à esquerda`}><span style={{ "--swatch": item.accent } as React.CSSProperties} /></button>)}</div></div><div className="compare__selector"><span>Direita</span><div className="compare__swatches">{finishes.map((item, i) => <button key={`right-${item.id}`} className={rightFinish === i ? "is-active" : ""} disabled={leftFinish === i} onClick={() => setRightFinish(i)} aria-label={`Usar ${item.name} à direita`}><span style={{ "--swatch": item.accent } as React.CSSProperties} /></button>)}</div></div></div><div className="compare__frame"><div className="compare__side before"><img src={transparent("angles", finishes[leftFinish].frontFile)} alt={`iPhone 17 Pro Max ${finishes[leftFinish].name}`} /></div><div className="compare__side after" style={{ clipPath: `inset(0 0 0 ${compare}%)` }}><img src={transparent("angles", finishes[rightFinish].frontFile)} alt={`iPhone 17 Pro Max ${finishes[rightFinish].name}`} /></div><div className="compare__divider" style={{ left: `${compare}%` }} /><div className="compare__handle" style={{ left: `${compare}%` }}><ChevronLeft size={15} /><ChevronRight size={15} /></div><input className="compare__input" type="range" min="0" max="100" value={compare} onChange={(e) => setCompare(Number(e.target.value))} onInput={(e) => setCompare(Number(e.currentTarget.value))} aria-label="Comparar cores do iPhone 17 Pro Max" /></div><div className="compare__labels"><span>{finishes[leftFinish].name}</span><span>{finishes[rightFinish].name}</span></div></div></section>

      <section className="trust"><div className="container"><div className="trust__list">{[["Produto único", "Toda a interface foi criada para o iPhone 17 Pro Max."], ["Imagens oficiais", "As fotos enviadas são a fonte visual definitiva do produto."], ["Cores reais", "Cada acabamento usa seu próprio arquivo, sem alteração artificial."], ["Compra segura", "Nota fiscal, garantia e atendimento especializado."], ["Entrega nacional", "Envio com rastreio para todo o Brasil."], ["Suporte próximo", "Ajuda para escolher o acabamento ideal para você."]].map(([title, text], i) => <article className="trust__item" key={title}><span className="trust__num">0{i + 1}</span><h4>{title}</h4><p>{text}</p></article>)}</div></div></section>

      <section className="footer-cta"><div className="footer-cta__glow" /><p className="section-label">iPhone 17 Pro Max</p><h2>Escolha seu acabamento e fale com um especialista.</h2><p>Cosmic Orange, Deep Blue ou Silver. O próximo passo é seu.</p><a href={whatsapp(current.name)} className="btn btn--primary" target="_blank" rel="noreferrer">Consultar disponibilidade <MessageCircle size={16} /></a></section>
    </main>

    <footer id="contato"><div className="container"><div className="footer__top"><div className="footer__brand">V�?RTICE<p>Experiência premium dedicada ao iPhone 17 Pro Max, com fotos oficiais, curadoria e atendimento próximo.</p></div><div className="footer__col"><h5>Navegação</h5><ul>{nav.map(([label, id]) => <li key={id}><a href={`#${id}`}>{label}</a></li>)}</ul></div><div className="footer__col"><h5>Produto</h5><ul><li>iPhone 17 Pro Max</li><li>Cosmic Orange</li><li>Deep Blue</li><li>Silver</li></ul></div><div className="footer__col"><h5>Contato</h5><ul><li><a href={whatsapp("falar pelo WhatsApp")} target="_blank" rel="noreferrer">WhatsApp</a></li><li>contato@vertice.com.br</li><li>(11) 99999-9999</li></ul></div></div><div className="footer__bottom"><p>© 2026 V�?RTICE. Loja independente �?" não afiliada à Apple Inc.</p><p>iPhone 17 Pro Max</p></div></div></footer>
    <a className="float-wa" href={whatsapp("falar com um especialista")} target="_blank" rel="noreferrer" aria-label="Falar no WhatsApp"><MessageCircle size={22} /></a>
    {lightbox && <div className="lightbox is-open" role="dialog" aria-modal="true" aria-label="Visualização do iPhone 17 Pro Max"><button className="lightbox__backdrop" onClick={() => setLightbox(null)} aria-label="Fechar visualização" /><div className="lightbox__panel"><button className="lightbox__close" onClick={() => setLightbox(null)} aria-label="Fechar">�-</button><div className="lightbox__media"><div className="lightbox__glow" /><img src={lightbox} alt="iPhone 17 Pro Max" /></div><div className="lightbox__aside"><div className="lightbox__eyebrow">Visual oficial</div><h3>iPhone 17 Pro Max</h3><p>Imagem fornecida oficialmente para esta experiência de produto.</p></div></div></div>}
  </div>;
}
